# Generated by Django 6.0.8 on 2026-08-13 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'crews'},
        ),
        migrations.AlterField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='+0', help_text="Enter the country's time zone (min: -12, max: +14)", max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='Enter the two-letter ISO country code', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='experience',
            field=models.PositiveIntegerField(help_text='Enter work experience in years. (1-50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(help_text='Enter the distance in kilometers', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.PositiveIntegerField(help_text='Enter the duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1200)]),
        ),
    ]
